# Generated by Django 4.1.7 on 2023-05-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField(blank=True, max_length=700)),
                (
                    "facture",
                    models.FileField(blank=True, null=True, upload_to="DocAide/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helping",
                        to="user.category",
                    ),
                ),
            ],
        ),
    ]
