# Generated by Django 4.2 on 2023-06-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("aide", "0003_aide_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aides",
                to="user.demandeur",
            ),
        ),
    ]
