# Generated by Django 4.1.7 on 2023-06-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aide", "0005_alter_aide_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="support",
            field=models.BooleanField(default=False),
        ),
    ]
