# Generated by Django 4.1.7 on 2023-06-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("aide", "0006_aide_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="likes",
            field=models.ManyToManyField(
                related_name="supportLike", to="user.association"
            ),
        ),
    ]
