# Generated by Django 4.1.7 on 2023-06-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aide", "0007_aide_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aide",
            old_name="likes",
            new_name="priseEnCharge",
        ),
    ]
