# Generated by Django 4.2 on 2023-06-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("aide", "0008_rename_likes_aide_priseencharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.association",
            ),
        ),
    ]
