# Generated by Django 4.1.7 on 2023-07-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aide", "0009_aide_association"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aide",
            name="priseEnCharge",
        ),
        migrations.AddField(
            model_name="aide",
            name="IsArnaque",
            field=models.BooleanField(default=False),
        ),
    ]
