# Generated by Django 4.1.7 on 2023-07-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_room_message_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
