# Generated by Django 4.1.7 on 2023-07-31 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "messaging",
            "0005_remove_message_isread_remove_message_published_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
