# Generated by Django 4.1.7 on 2023-08-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_message_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
    ]
