# Generated by Django 4.1.7 on 2023-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0008_remove_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
