# Generated by Django 4.1.7 on 2023-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
