# Generated by Django 4.2 on 2023-05-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_association_id_user_alter_association_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
