# Generated by Django 4.1.7 on 2023-05-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_category_remove_association_activiteprincipal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="association",
            name="mainCategory",
        ),
        migrations.RemoveField(
            model_name="category",
            name="mainCategory",
        ),
        migrations.AddField(
            model_name="association",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryLink",
                to="user.category",
            ),
        ),
    ]
