# Generated by Django 4.1.7 on 2023-08-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="fistName",
            new_name="firstName",
        ),
    ]
