# Generated by Django 4.1.7 on 2023-08-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_rename_fistname_contact_firstname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=80),
        ),
    ]
